resolver: lts-12.7

packages:
- .

extra-deps:
- bitwise-1.0.0.1
- git: https://github.com/strake/ca.hs
  commit: 43a031dd42c6c02c16bb91020a1f7c6aaa98321a
- git: https://github.com/strake/z3.hs
  commit: 4e0898e78c1df0e3eab32201746f3d6a08b05dc4
