resolver: nightly-2018-04-01

packages:
- .

extra-deps:
- bitwise-1.0.0.1
- git: https://github.com/strake/alg.hs
  commit: fd323cebe3a82a416fe78eacfb910671b445f542
- git: https://github.com/strake/ca.hs
  commit: 43a031dd42c6c02c16bb91020a1f7c6aaa98321a
- git: https://github.com/strake/util.hs
  commit: 989d3fe4f5da455ee7dd1337752ee7a2ee1b4d09
- git: https://github.com/strake/z3.hs
  commit: 4e0898e78c1df0e3eab32201746f3d6a08b05dc4

allow-newer: true
